/**
 * KiscoLearning.tsx
 * ─────────────────────────────────────────────────────────────────────────────
 * Remotion composition for Kisco Learning's "The Perfect School Morning &
 * Safe Bus Ride" — landscape 1920×1080 @ 30fps, YouTube Kids optimized.
 *
 * Scene flow:
 *   0  →  5s  Hook card    "Is YOUR morning routine keeping you SAFE?"
 *   5  → 85s  Preparation  Packing backpack, morning routine
 *  85  → 145s Boarding     Safe bus stop and boarding
 * 145  → 225s The Ride     Sitting properly, forward momentum
 * 225  → 248s Checklist    Safety recap
 * 248  → 254s Outro        Subscribe CTA
 *
 * Assets (generated by kisco_generate_cartoon_assets.py):
 *   public/images/kisco/scene_hook.jpg
 *   public/images/kisco/scene_prep.jpg
 *   public/images/kisco/scene_boarding.jpg
 *   public/images/kisco/scene_ride.jpg
 *   public/images/kisco/scene_checklist.jpg
 *   public/audio/kisco/narration.mp3
 */

import React from "react";
import {
  AbsoluteFill,
  Audio,
  Img,
  interpolate,
  Sequence,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";

// ─── Constants ────────────────────────────────────────────────────────────────

const FPS = 30;

// Brand colors
const BRAND_YELLOW = "#FFD600";
const BRAND_GREEN  = "#2D7A4F";

// ─── Scene definitions ────────────────────────────────────────────────────────

interface SceneDef {
  id: string;
  startSec: number;
  endSec: number;
  title: string;
  subtitle: string;
  image: string | null;          // staticFile key, null = no image
  bgColor: string;
  titleColor: string;
  accentColor: string;
  kenBurnsDir: "in" | "out";    // zoom in or out over the scene
}

const SCENES: SceneDef[] = [
  {
    id:          "hook",
    startSec:    0,
    endSec:      5,
    title:       "Is YOUR morning routine keeping you SAFE?",
    subtitle:    "School Bus Safety Tips",
    image:       "images/kisco/scene_hook.jpg",
    bgColor:     BRAND_YELLOW,
    titleColor:  "#1A1A1A",
    accentColor: BRAND_GREEN,
    kenBurnsDir: "in",
  },
  {
    id:          "preparation",
    startSec:    5,
    endSec:      85,
    title:       "Step 1: Preparation",
    subtitle:    "Pack everything the night before!",
    image:       "images/kisco/scene_prep.jpg",
    bgColor:     "#FF7043",
    titleColor:  "#FFFFFF",
    accentColor: BRAND_YELLOW,
    kenBurnsDir: "out",
  },
  {
    id:          "boarding",
    startSec:    85,
    endSec:      145,
    title:       "Step 2: Safe Boarding",
    subtitle:    "Stay behind the curb until the bus stops!",
    image:       "images/kisco/scene_boarding.jpg",
    bgColor:     "#0288D1",
    titleColor:  "#FFFFFF",
    accentColor: BRAND_YELLOW,
    kenBurnsDir: "in",
  },
  {
    id:          "ride",
    startSec:    145,
    endSec:      225,
    title:       "Step 3: The Ride",
    subtitle:    "Stay seated and face forward!",
    image:       "images/kisco/scene_ride.jpg",
    bgColor:     "#388E3C",
    titleColor:  "#FFFFFF",
    accentColor: BRAND_YELLOW,
    kenBurnsDir: "out",
  },
  {
    id:          "checklist",
    startSec:    225,
    endSec:      248,
    title:       "Safety Checklist",
    subtitle:    "You've got this!",
    image:       "images/kisco/scene_checklist.jpg",
    bgColor:     "#7B1FA2",
    titleColor:  "#FFFFFF",
    accentColor: BRAND_YELLOW,
    kenBurnsDir: "in",
  },
  {
    id:          "outro",
    startSec:    248,
    endSec:      254,
    title:       "Subscribe to Kisco Learning!",
    subtitle:    "More fun learning every week 🔔",
    image:       null,
    bgColor:     BRAND_GREEN,
    titleColor:  BRAND_YELLOW,
    accentColor: "#FFFFFF",
    kenBurnsDir: "in",
  },
];

// ─── KenBurns helper ──────────────────────────────────────────────────────────

function useKenBurns(durationInFrames: number, dir: "in" | "out") {
  const frame = useCurrentFrame();
  const progress = frame / Math.max(durationInFrames - 1, 1);
  // Subtle zoom: 1.0 ↔ 1.12 over the scene duration
  const scale = dir === "in"
    ? interpolate(progress, [0, 1], [1.0, 1.12])
    : interpolate(progress, [0, 1], [1.12, 1.0]);
  return { transform: `scale(${scale})`, transformOrigin: "center center" };
}

// ─── Title spring animation ───────────────────────────────────────────────────

function useTitleAnimation() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const scale = spring({ fps, frame, config: { damping: 12, stiffness: 120 }, from: 0.7, to: 1 });
  const opacity = interpolate(frame, [0, 12], [0, 1], { extrapolateRight: "clamp" });
  return { transform: `scale(${scale})`, opacity };
}

// ─── SubTitle fade ────────────────────────────────────────────────────────────

function useSubtitleAnimation() {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [10, 25], [0, 1], { extrapolateRight: "clamp" });
  const translateY = interpolate(frame, [10, 25], [20, 0], { extrapolateRight: "clamp" });
  return { opacity, transform: `translateY(${translateY}px)` };
}

// ─── KiscoScene ───────────────────────────────────────────────────────────────

const KiscoScene: React.FC<{ scene: SceneDef }> = ({ scene }) => {
  const { durationInFrames } = useVideoConfig();
  const kenBurns = useKenBurns(durationInFrames, scene.kenBurnsDir);
  const titleAnim = useTitleAnimation();
  const subtitleAnim = useSubtitleAnimation();

  return (
    <AbsoluteFill style={{ backgroundColor: scene.bgColor, overflow: "hidden" }}>

      {/* ── Cartoon image (full-bleed with Ken Burns) ────────────────────── */}
      {scene.image && (
        <AbsoluteFill style={{ overflow: "hidden" }}>
          <Img
            src={staticFile(scene.image)}
            style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
              ...kenBurns,
            }}
          />
        </AbsoluteFill>
      )}

      {/* ── Gradient overlay (bottom third) ─────────────────────────────── */}
      <AbsoluteFill
        style={{
          background: `linear-gradient(
            to bottom,
            transparent 0%,
            transparent 40%,
            ${scene.bgColor}CC 65%,
            ${scene.bgColor}F5 80%,
            ${scene.bgColor} 100%
          )`,
        }}
      />

      {/* ── Top accent bar ───────────────────────────────────────────────── */}
      <div
        style={{
          position: "absolute",
          top: 0, left: 0, right: 0,
          height: 8,
          backgroundColor: scene.accentColor,
        }}
      />

      {/* ── Channel bug (top-left) ───────────────────────────────────────── */}
      <div
        style={{
          position: "absolute",
          top: 24,
          left: 28,
          backgroundColor: BRAND_GREEN,
          borderRadius: 12,
          padding: "10px 22px",
          fontFamily: '"Arial Black", "Trebuchet MS", sans-serif',
          fontWeight: 900,
          fontSize: 30,
          color: "#FFFFFF",
          letterSpacing: 0.5,
        }}
      >
        Kisco Learning
      </div>

      {/* ── Text block (bottom) ─────────────────────────────────────────── */}
      <div
        style={{
          position: "absolute",
          bottom: 60,
          left: 60,
          right: 60,
        }}
      >
        {/* Main title */}
        <div
          style={{
            ...titleAnim,
            fontFamily: '"Arial Black", "Trebuchet MS", sans-serif',
            fontWeight: 900,
            fontSize: scene.id === "hook" ? 72 : 80,
            color: scene.titleColor,
            lineHeight: 1.15,
            textShadow: "0 4px 20px rgba(0,0,0,0.5)",
            marginBottom: 16,
          }}
        >
          {scene.title}
        </div>

        {/* Accent divider */}
        <div
          style={{
            width: 80,
            height: 6,
            backgroundColor: scene.accentColor,
            borderRadius: 3,
            marginBottom: 18,
          }}
        />

        {/* Subtitle */}
        <div
          style={{
            ...subtitleAnim,
            fontFamily: '"Trebuchet MS", "Segoe UI", sans-serif',
            fontWeight: 700,
            fontSize: 40,
            color: scene.titleColor,
            opacity: (subtitleAnim.opacity as number) * (scene.id === "hook" ? 1 : 0.9),
            textShadow: "0 2px 10px rgba(0,0,0,0.4)",
          }}
        >
          {scene.subtitle}
        </div>
      </div>

      {/* ── Section number badge (scenes 2–5) ───────────────────────────── */}
      {scene.id !== "hook" && scene.id !== "outro" && (
        <div
          style={{
            position: "absolute",
            top: 24,
            right: 28,
            backgroundColor: scene.accentColor,
            borderRadius: "50%",
            width: 80,
            height: 80,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontFamily: '"Arial Black", sans-serif',
            fontWeight: 900,
            fontSize: 36,
            color: scene.bgColor,
          }}
        >
          {["preparation", "boarding", "ride", "checklist"].indexOf(scene.id) + 1}
        </div>
      )}
    </AbsoluteFill>
  );
};

// ─── KiscoLearning (root composition) ────────────────────────────────────────

export const KiscoLearning: React.FC = () => {
  return (
    <AbsoluteFill>
      {/* Original narration audio plays under the whole video */}
      <Audio
        src={staticFile("audio/kisco/narration.mp3")}
        volume={1}
        startFrom={0}
      />

      {/* Scene sequences timed to narration */}
      {SCENES.map((scene) => {
        const startFrame = Math.round(scene.startSec * FPS);
        const endFrame   = Math.round(scene.endSec   * FPS);
        const dur        = endFrame - startFrame;

        return (
          <Sequence
            key={scene.id}
            from={startFrame}
            durationInFrames={dur}
            name={scene.id}
          >
            <KiscoScene scene={scene} />
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};
